---
# tasks file for neutron

# Install and configure
- name: Install OpenStack neutron packages.
  yum: name={{ item }} state=installed
  with_items:
    - openstack-neutron
    - openstack-neutron-linuxbridge
    - libvirt-daemon-config-nwfilter
    - ebtables
    - ipset

- name: Copy the neutron configuration files for neutron compute.
  template: src=neutron.conf.j2 dest=/etc/neutron/neutron.conf

- name: Copy the neutron linux bridge configuration files for neutron compute.
  template: src=linuxbridge_agent.ini.j2 dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini

- name: Ensure neutron compute service is started and enabled on boot.
  service: name={{ item }} enabled=yes state=started
  ignore_errors: True
  with_items:
    - neutron-linuxbridge-agent
